services:
  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loctelli_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ../my-app
      dockerfile: Dockerfile
    container_name: loctelli_frontend
    ports:
      - "3001:3000"
    env_file:
      - ../my-app/.env.local
    depends_on:
      - api
    volumes:
      - ../my-app:/app
      - /app/node_modules

  # Database
  db:
    image: postgres:15
    container_name: loctelli_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7-alpine
    container_name: loctelli_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
